# Cette action GitHub récupère les données de l'ontologie et du profil d'application depuis Google sheet pour les sauvegarder dans GitHub
name: Google Sheet to TTL
on: workflow_dispatch
jobs:
  
  google-sheet-to-ttl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Récupération de l'ontologie"
        run : |
          curl -L --request GET 'https://xls2rdf.sparna.fr/rest/convert?noPostProcessings=true' \
          -H "Connection: keep-alive" \
          -F url='https://docs.google.com/spreadsheets/d/1CZIf3bxuuH3aghFn7B7P89DrLqp_jzv4moI_BpI9PzY/export?format=xlsx' \
          -F format=ttl \
          -o ./ontologie/rdafr.ttl
          
          curl -L --request GET 'https://xls2rdf.sparna.fr/rest/convert?noPostProcessings=true' \
          -H "Connection: keep-alive" \
          -F url='https://docs.google.com/spreadsheets/d/1CZIf3bxuuH3aghFn7B7P89DrLqp_jzv4moI_BpI9PzY/export?format=xlsx' \
          -F format=text/plain \
          -o ./ontologie/rdafr.nt 
          
          curl -L --request GET 'https://xls2rdf.sparna.fr/rest/convert?noPostProcessings=true' \
          -H "Connection: keep-alive" \
          -F url='https://docs.google.com/spreadsheets/d/1CZIf3bxuuH3aghFn7B7P89DrLqp_jzv4moI_BpI9PzY/export?format=xlsx' \
          -F format=application/rdf+xml \
          -o ./ontologie/rdafr.rdf
          
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Feat : Mise à jour de l'ontologie"
