# Récupère les données de l'ontologie au format xlsx depuis google drive pour les transformer au format turtle.
name: Google Sheet to TTL
on: workflow_dispatch     
jobs:
  google-sheet-to-ttl:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - run : |
          curl -L --request GET 'https://xls2rdf.sparna.fr/rest/convert' \
          -H "Connection: keep-alive" \
          --form 'url=https://docs.google.com/spreadsheets/d/1iCIHk6xF7GLKjWI4vPOUub8tbd1LXXzlSPKYa2GcFpo/export?format=xlsx' \
          --form "format=ttl" \
          -o ./profil-application/rdafr.ttl
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Feat : Mise à jour de l'ontologie"
